language: "haskell"
sudo: required
dist: trusty
ghc:
  - "8.0"
  - "8.2"
install:
  - "travis_retry cabal install 'cpphs >= 1.18.3' 'happy >= 1.19.5'"
  - "cabal install --dry-run -v3"
  - "travis_retry cabal install --force-reinstalls --only-dependencies -ftest"
script:
  - cabal install . fay-base/ --jobs=1 -ftest
  - cabal exec fay-tests -- --num-threads=4 -random 20
  - npm install
  - npm test
notifications:
  email:
    recipients: adam@bergmark.nl
    on_success: change
    on_failure: change
